harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Non Native Helm Template Workflow
  parallel: false
  runtimeInputs:
    runtimeInputVariables:
    - Environment
    - Service
    - InfraDefinition_KUBERNETES
    timeout: 86400000
    timeoutAction: END_EXECUTION
    userGroupNames:
    - Account Administrator
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Non Native Helm Template Workflow
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: ${env}
  - entityType: SERVICE
    name: Service
    value: ${svc}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: ${infra}
  - name: SiteURL
    value: ruchi
