harnessApiVersion: '1.0'
type: MULTI_SERVICE
concurrencyStrategy: INFRA
envName: prod
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: SSH
  computeProviderName: CS - Gabs - Amazon Web Services
  daemonSet: false
  infraDefinitionName: gabs_aws_ec2
  name: Fetching Output Variables from CF
  phaseSteps:
  - type: INFRASTRUCTURE_NODE
    name: Prepare Infra
    steps:
    - type: SHELL_SCRIPT
      name: CLOUDFORMATION INSTANCE ID CASTING
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        publishAsVar: true
        sshKeyRefName: null
        sweepingOutputName: info
        sweepingOutputScope: WORKFLOW
        templateExpressions: null
        timeoutMillis: 600000
      templateUri: CS - Gabriel - Renamed/CLOUDFORMATION INSTANCE ID CASTING:latest
    stepsInParallel: false
  - type: DISABLE_SERVICE
    name: Disable Service
    steps:
    - type: SHELL_SCRIPT
      name: Fetching directly from the CloudFormation Outputs
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: |-
          #!/bin/bash

          echo "Printing the exported/hacked Instance ID from Cloudformation"
          echo ${context.info.instanceid}

          echo "Now, trying to fetch the DNS from directly from CF Outputs"
          echo "${cloudformation.PublicDNS}"

          echo "END OF SCRIPT"
        scriptType: BASH
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: SHELL_SCRIPT
      name: Fetching again directly from CF Outputs
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: |-
          #!/bin/bash

          echo "Printing the exported/hacked Instance ID from Cloudformation"
          echo ${context.info.instanceid}

          echo "Now, trying to fetch the DNS from directly from CF Outputs"
          echo "${cloudformation.PublicDNS}"

          echo "END OF SCRIPT"
        scriptType: BASH
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: EC2_Service_Bug
  statefulSet: false
postDeploymentSteps:
- type: CLOUD_FORMATION_DELETE_STACK
  name: CloudFormation Delete Stack
  properties:
    awsConfigId: ybeQXuMBTyWuCoztIg_Vhw
    cloudFormationRoleArn: arn:aws:iam::915632791698:role/CloudFormation_PowerUser_Acess
    provisionerName: Basic_EC2_CF
    region: sa-east-1
    timeoutMillis: 300000
    useCustomStackName: false
preDeploymentSteps:
- type: CLOUD_FORMATION_CREATE_STACK
  name: CloudFormation Create Stack
  properties:
    awsConfigId: ybeQXuMBTyWuCoztIg_Vhw
    backendConfigs: null
    cloudFormationRoleArn: arn:aws:iam::915632791698:role/CloudFormation_PowerUser_Acess
    provisionerName: Basic_EC2_CF
    region: sa-east-1
    timeoutMillis: 300000
    variables: null
rollbackPhases:
- type: SSH
  computeProviderName: CS - Gabs - Amazon Web Services
  daemonSet: false
  infraDefinitionName: gabs_aws_ec2
  name: Rollback Fetching Output Variables from CF
  phaseNameForRollback: Fetching Output Variables from CF
  phaseSteps:
  - type: DISABLE_SERVICE
    name: Disable Service
    phaseStepNameForRollback: Enable Service
    statusForRollback: SUCCESS
    steps:
    - type: CLOUD_FORMATION_DELETE_STACK
      name: CloudFormation Delete Stack
      properties:
        awsConfigId: gwI5K4bGTmirTLVW_mzwvA
        cloudFormationRoleArn: arn:aws:iam::915632791698:role/CloudFormation_PowerUser_Acess
        provisionerName: Basic_EC2_CF
        region: sa-east-1
        timeoutMillis: 300000
        useCustomStackName: false
    stepsInParallel: false
  - type: STOP_SERVICE
    name: Stop Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    phaseStepNameForRollback: Disable Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: EC2_Service_Bug
  statefulSet: false
templatized: false
