harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: prod
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: KUBERNETES
  computeProviderName: CS - Gabs - Kubernetes Cluster - GCP
  daemonSet: false
  infraDefinitionName: gabs_gcp_k8s
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    stepSkipStrategies:
    - assertionExpression: 1 == 1
      scope: SPECIFIC_STEPS
      steps:
      - Rollout Deployment
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    - type: APPROVAL
      name: Approval
      properties:
        approvalStateType: USER_GROUP
        publishAsVar: true
        sweepingOutputName: GABS
        sweepingOutputScope: WORKFLOW
        timeoutMillis: 86400000
        userGroupNames:
        - Account Administrator
        variables:
        - name: randomvalue
          value: override_me
        - name: test
          value: override_me
    - type: SHELL_SCRIPT
      name: Just to print those variables real quick using the context of this WF
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        includeInfraSelectors: true
        outputVars: ''
        publishAsVar: false
        scriptString: |-
          #!/bin/bash

          echo "Howdy, I'll print some Approval context variables now!"

          echo "${GABS.approvedBy.name}"
          echo "${GABS.variables.randomvalue}"
          echo "${GABS.variables.test}"
        scriptType: BASH
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 60000
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Rahul_Gabs_ConfigFile_Content
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: CS - Gabs - Kubernetes Cluster - GCP
  daemonSet: false
  infraDefinitionName: gabs_gcp_k8s
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Rahul_Gabs_ConfigFile_Content
  statefulSet: false
templatized: false
