{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICI5MTU2MzI3OTE2OTguZGtyLmVjci5zYS1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHsKICAgICAgImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsUldFNXlUbXhTUTJGclZsTldSVXBMWTJwSmVsVkZTWHBOVkZwclZUSldOVlpyYkhOVlJGSldaR3BXUjFOVmVGcFRhMFpVVlVkU1ZVMHdUbmxXTUZwU1pHeEtObVJEZEhSbFZHZDRWbGhHUm1OcWJEWldhbFpEWTJwV1QySjZSWGhhUkZwMVRsUk5NbG95Y0RGYVJFcERVVlJOY21GdFRuSlRWVkkwVVRCa1dWZEhVakpqZWtKMlV6SjBiMkZGVWxsaGJteFNUa1UxZEZWWGRIUlRTRW95VVZSRmVWTlliM2xPYkZwNlRrVnNWVlJET1haYVIxWnRVa1JLWVZwWFRYWlNWRTVGVGpGb1ZGWlZSbmhhU0dSdVYxUlNTbVJHY0ROaWFYUkpaREZrVFdKRlozbGlhazUxWWtoV1MxbFZZekJUU0hCcFQwWkNXbU5IVGxaV01qRnVaV3hTVkZwSVduZFNNREZEVG1wR2VWUXlhRmRaTWs1TlZUSnNTMkpYV2toT1JVNUNaREZHU0ZsdVpHeGlNbFpwWTJzMVJXSXljREprVmxwRFZEQkZNRXd3V2sxalIxcHJUa2RzUWsxNlFsSmxWMDU0WVhwR2NsRXlXakJVYkZaWldrWktWMlZzUWxkV2JFSkhUREo0UWxwc1pFTlVWa1pyWXpCT2NHSnRlSFphUjFWNlZGVnZkMk5ZUVRST1Z6VlVXV3hzWVU1clZrcFVNR3h3VTFaa2JXSXhRbXBhTW14WVdrUlJOVmRWYUU5aGExbzJZakpvVEZKSFVsbFZSVkY2VWpCV2JVMXRiRmxWTWs1T1l6SlNiVk51U2tWU2VrSlZWVWRLUWxOR2JHdExlbVJaVlVSb1ZGSjVPVk5VV0hCV1ZsaG9UMWxWYkV4a1IzQk1XVlZhY2xkV2FIUlhWV1J1V2xkMGMyTXhjRUpOUld4MVkydEtiRkpyWkZsaVZFMDFWak5STUdFeldYcGhRM00xWWpKb1VsSlVRbkZhUkZac1RWUldXV1JzYUhWUlYyOTVWRE5LU21GSVl6UldTR2hNV1dwU2FFNXVhRU5VV0d4S1drUlZNbHByWkhWUk1tc3lWRzVLVmxkdFpGVk5WbWhIVmtNNWJWZFdUVEprYTBwclVuazVUMk5xV2pSalJHeDZVbFJSY2xkSVduUmtNbFpGVVhwYWVscDZSbE5oTTJzeFlrUnNWVll4Y0ZoU01tZ3dWbXBzZDAweFNuWmxTRmswWld0R2FXUXhhR0ZXYlhNd1QxTTVlVlZwT0hsVmExWkRXbFpDZFdOVVRUQlVlbWN3VFhwR2FrNVhTazFYUkZwSldUTldUMVpyYXpSVk1uQldWR3hhZUV3eFVtbE9TR2h2Vldwck0yTlZkRXBVTWtwRVZVZHdSMVF5VGt0UmJXUTFZMnhGTWxNeFRrdE9WVmt4WVVaV1FsWXhWbXRhYWxKTFltcGFhMkZYYkhaaU1qRjFWV2s1TVZadGFHOVNiazVJVWxoU1RtSlZjM1pVUms1b1draE9ZVk5xV25samJVNTJWRlJLU1UxSE5UUmpNRlkwWlVob1NXUXhUbGxrVjJoMVlsWldjRk15TVU1YVJHY3dVakZCTUZGWVFsRk5SVVpQV25wSmQxWXpValZhUnpWS1pGVkdOVTVWVmxoV1YxWXhWRlpHZEZWVk5UVlZWbEpKVGtSS2JGZFdWbEprUjFKMlVrVnJNRTV0Vm5WaE1qUTFXVlJvTm1ScVFrOWlhbXhTVG0xNGVHUnRNVmRsUlZwUFRrVnZNbU5FUlRCVldFNVZZbTVTUlZwWFdYcE1NR2MwWkVWV1dsWlhiSE5VYVhSUFVqTnNlR0pGTVhSV1ZtUTFXak5LVlZsVlozSk9hMUoxV210R1lWUnRWa2xWUkZKNlRsZGtlbUZzWkZaaGJVazBXbGRzUzJOWVFqQmpWRTQxVW0xR2VGcHNVbmhoZW1STlVqRm9NRk5YT1haVGJGSlZXbFZ3ZDAxcVNYaFpNMVpEVWtkd1JWa3pTVFZUTUVwRlRXeG9XbEpIYjNKU2JVcFJVekZ3VFdKc1NrdGxSbEpOVkcxc1JWbHJaRmhqU0dRelRucEdSbFZHVG0xV2VrWldUVmhzVjJNeVdtNWthbHBWV2tkMGRtSXhTVEpoVTNONlVWZGFXbG96YkV0alJFRXlWREZhYUZFeVpISmFWazVMU3pCc2IxZEZVbGhXUlZacVlXcGFNVlpIZEdoUk1FNTFWa1Z3TVZWR2NIZFdTR2hVWlc1d2NWUlZWVEJXUkZaMVQxZG9NMVl3YkhwV01HeFhZMWM1YkZVeFkzWlZlbU0xVVdwU2RsZEdVakpSYlRBeVpWWlNkMDB4VW14alZXaHdZa1pCTTJOcmFERk5hemxOVTBNNWRGWlhjSFpOYWxwSlVUSndjVm94Vm0xTU1GWnNUbTFLZDJKVlNYZFdhMWt4WVZjd05GbHJVbmhoYkVaUVYwYzFlV0Y2VGsxU1YyaFlUMFpGT1ZCVFNYTkpiVkpvWkVkR2NscFlhMmxQYVVwQ1ZWVnNRMUZWYUhGVlNGSjJaRWRHY0ZKclNsSmtWRTQwVkZoV2MwNUhPVFJVYWtGNlV6TndWMVJVVVRSVVYxcEdVMjB4ZVU1SGVEVk5TSEI2WWxWNE1WVlZaSE5OUTNSRllVVTRkbFJzVW1wYU1WWlBaVmRPV0UxWVNtdFBTR1JDVVZWR1FscHRjRU5QUlVwdVlUTkdiMkV5YkVoUFdHTjNVV3RLTTFsWFpHbGxhMG93VVZka1JsRlZNVWhhTUdSRVZUTkdTRlV3YkdsTk1GSlNVbFZvUWxaRlJteFJiV1J6V2pKb2Nsb3dTbUZWVlRGR1VWWk5NR1F3VmxKVlZUQjJUVEpzVm1WWVFrZFZNRGw2VTBWT05GUXhWVEJSVjJSR1ZWZGtSV041T1U1U01XaDJVekF3ZDJWWVVYZGhNRlkyWkVkNE5HUlhPWFJPUmtaM1VWWkJNVTFWT1VSYWJtaHRUMGQ0TkdSRE9UUmhSM1I1VGxWd2FVNVlXbWhqTUVVeVZXeE9kVTR3TlhOT01GWlZZMVZzVTFwR1RrbFZWMmg1WWpJMVJVNUhiRmRUV0VvMVVrVkZPVkJUU1hOSmJscHNZMjVPY0dJeU5HbFBhVWw1U1dsM2FXUkliSGRhVTBrMlNXdFNRbFpGUm1aVE1GWmFTV2wzYVZwWWFIZGhXRXBvWkVkc2RtSnBTVFpOVkZrd1QxUmpNRTE2YXpGT1NEQTkiCiAgICB9LAogICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKICAgICAgImF1dGgiOiAiWjJGalpYSnBiMjVwT2preE5ETmpOMlUzTFRkak0yRXRORFE0T1MxaFpHSTJMVFJtT1RKbU5HTXhNVFUxWmc9PSIKICAgIH0KICB9LAogICJjcmVkc1N0b3JlIjogImRlc2t0b3AuZXhlIgp9Cg==
type: kubernetes.io/dockerconfigjson
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        {{- if or .Values.env.config .Values.env.secrets}}
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            name: {{.Values.name}}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        {{- end}}