{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-sidecar-config-map
  namespace: {{.Values.namespace}}
  annotations:
  labels:
    app: {{.Values.name}}
    product: {{.Values.product}}
    product-line: {{.Values.productLine}}
data:
  BACKEND_PORT: {{.Values.sidecar.env.config.applicationPort | toString}}
  SERVER_SSL_KEYSTORE_TYPE: "{{.Values.sidecar.env.config.keyStoreType}}"
  SSL_CIPHERS: "{{.Values.sidecar.env.config.sslCiphers}}"
  SERVER_SSL_KEY_STORE_LOCATION: "{{.Values.sidecar.env.config.secretDataDir}}"
  CLIENT_NAME_VERIFICATION_ALLOWED_CLIENTS: "{{.Values.sidecar.env.config.allowedclients}}"
  CLIENT_NAME_VERIFICATION_ENABLED: "{{.Values.sidecar.env.config.clientverf}}"
{{- end}}