apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harness-coks-deployment
spec:
  replicas: 1
  serviceName: harness-coks-svc
  selector:
    matchLabels:
      app: harness-coks
  template:
    metadata:
      labels:
        app: harness-coks
    spec:
      containers:
      - name: harness-coks
        image: {{ .Values.image }}