apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harness-example-deployment
spec:
  replicas: 1
  serviceName: harness-example-svc
  selector:
    matchLabels:
      app: harness-example
  template:
    metadata:
      labels:
        app: harness-example
    spec:
      containers:
      - name: harness-example
        image: {{ .Values.image }}