name: harness-example
replicas: 1

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

createNamespace: true
namespace: ${infra.kubernetes.namespace}

# EWS BLOCK
product: testing
productLine: testingews

## Sidecar
sidecar:
  enabled: ${serviceVariable.enableSidecar}
  image: ${serviceVariable.sidecarImageWithTag}
  port: 9080
  env:
    config:
      secretDataDir: /home/jboss/secrets
      keyStoreType: ${serviceVariable.sidecarKeystoreType}
      sslCiphers: ${serviceVariable.sidecarSslCiphers}
      serverKeystoreData: ${configFile.getAsBase64("sidecarServerKeystoreData")}
      allowedclients: ${serviceVariable.sidecarclients}
      clientverf: ${serviceVariable.sidecarClientnameverf}
      applicationPort: 4000
    secrets:
      serverSslKeystoreCredential: ${serviceVariable.sidecarServerSslKeystoreCredential}