harnessApiVersion: '1.0'
type: GIT
branch: main
keyAuth: true
sshKeyName: GitHub_Gabs_MBP_PEM
url: git@github.com:gacerioni/GitSync_Application_Level_Reserved_Repo.git
urlType: REPO
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - PROD
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
