harnessApiVersion: '1.0'
type: BLUE_GREEN
concurrencyStrategy: INFRA
envName: prod
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: KUBERNETES
  computeProviderName: CS - Gabs - AWS - EKS - CS Admin
  daemonSet: false
  infraDefinitionName: EKS_K8s_SA_EAST_1
  name: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_BLUE_GREEN_DEPLOY
      name: Stage Deployment
      properties:
        delegateSelectors: null
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APPROVAL
      name: Approval
      properties:
        approvalStateType: USER_GROUP
        timeoutMillis: 86400000
        userGroupNames:
        - Account Administrator
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        delegateSelectors:
        - eks-anaplan-nonroot
        service1: ${k8s.primaryServiceName}
        service2: ${k8s.stageServiceName}
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Workload with Ingress
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: CS - Gabs - AWS - EKS - CS Admin
  daemonSet: false
  infraDefinitionName: EKS_K8s_SA_EAST_1
  name: Rollback Blue/Green
  phaseNameForRollback: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Route Update
    phaseStepNameForRollback: Route Update
    statusForRollback: SUCCESS
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${k8s.primaryServiceName}
        service2: ${k8s.stageServiceName}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Workload with Ingress
  statefulSet: false
templatized: false
