harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
helmChartConfig:
  chartName: ${workflow.variables.chartName}
  chartVersion: ${workflow.variables.chartVersion}
  connectorName: icg-helm-prod
storeType: HelmChartRepo
