harnessApiVersion: '1.0'
type: SSH
commandUnitType: OTHER
commandUnits:
- command: |+
    #!/bin/bash
    mkdir -p "${app.defaults.RUNTIME_PATH}"

    echo ${TECNOLOGIA}

    case ${TECNOLOGIA} in
         "MACBOOK")
            echo "MACBOOK"
            ;;
        "frontsAngular")
            npm ci
            export NODE_OPTIONS=--max_old_space_size=5048
            ng build --prod
            gcloud app deploy --project ${GC_PROJECT} -q --verbosity=info
            ;;
    esac

    echo DONE

  commandUnitType: SETUP_ENV
  deploymentType: SSH
  name: Setup Env
  scriptType: BASH
  workingDirectory: Setup Runtime Paths
- artifactVariableName: artifact
  commandUnitType: DOWNLOAD_ARTIFACT
  deploymentType: SSH
  name: Download Artifact
  scriptType: BASH
  workingDirectory: /tmp
- command: |-
    echo "PRINTING THE ARTIFACT FILE NAME:"
    echo "$ARTIFACT_FILE_NAME"
    echo "${ARTIFACT_FILE_NAME}"
  commandUnitType: EXEC
  deploymentType: SSH
  name: Expand Artifact
  scriptType: BASH
variables:
- name: tr_filename
- name: helper_var
  value: ${instance.hostName}
- name: TECNOLOGIA
  value: MACBOOK
