harnessApiVersion: '1.0'
type: SSH
commandUnitType: OTHER
commandUnits:
- command: |-
    mkdir -p "${app.defaults.RUNTIME_PATH}"
    echo "${helper_var}"


    echo ${TECNOLOGIA}
  commandUnitType: SETUP_ENV
  deploymentType: SSH
  name: Setup Env
  scriptType: BASH
  workingDirectory: Setup Runtime Paths
- artifactVariableName: artifact
  commandUnitType: DOWNLOAD_ARTIFACT
  deploymentType: SSH
  name: Download Artifact
  scriptType: BASH
  workingDirectory: /tmp
- command: |-
    echo "PRINTING THE ARTIFACT FILE NAME:"
    echo "$ARTIFACT_FILE_NAME"
    echo "${ARTIFACT_FILE_NAME}"
  commandUnitType: EXEC
  deploymentType: SSH
  name: Expand Artifact
  scriptType: BASH
variables:
- name: tr_filename
- name: helper_var
  value: ${instance.hostName}
- name: TECNOLOGIA
  value: MACBOOK
