harnessApiVersion: '1.0'
type: SSH
commandUnitType: OTHER
commandUnits:
- command: mkdir -p "${app.defaults.RUNTIME_PATH}"
  commandUnitType: SETUP_ENV
  deploymentType: SSH
  name: Setup Env
  scriptType: BASH
  workingDirectory: Setup Runtime Paths
- artifactVariableName: artifact
  commandUnitType: DOWNLOAD_ARTIFACT
  deploymentType: SSH
  name: Download Artifact
  scriptType: BASH
  workingDirectory: /tmp
variables:
- name: tr_filename
